openapi: 3.0.3
info:
  title: Golang Blockchain
  description: Golang blockchain
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /blockchain:
    get:
      summary: Get blockchain
      operationId: getBlockchain
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Block'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: commit transactions
      operationId: commitTransactions
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /transactions:
    get:
      summary: Get transactions pool
      operationId: getTransactionsPool
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Create Transaction
      operationId: CreateTransaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    TransactionRequest:
      type: object
      required:
        - timestamp
        - sender_public_key
        - sender_address
        - recipient_address
        - amount
        - signature
      properties:
        timestamp:
          type: string
          format: date-time
        sender_public_key:
          type: string
        sender_address:
          type: string
        recipient_address:
          type: string
        amount:
          type: number
          format: double
        signature:
          type: string

    Block:
      type: object
      required:
        - timestamp
        - nonce
        - previous_hash
        - hash
        - transactions
      properties:
        timestamp:
          type: string
        nonce:
          type: integer
        previous_hash:
          type: string
        hash:
          type: string
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Transaction:
      type: object
      required:
        - sender
        - recipient
        - amount
      properties:
        sender:
          type: string
        recipient:
          type: string
        amount:
          type: number
          format: double
    ErrorResponse:
      type: object
      required:
        - message
        - err_code
      properties:
        err_code:
          type: integer
        message:
          type: string
